name: database CI

on:
 workflow_dispatch:
 
env:
  TOKEN: ${{ secrets.SONAR_TOKEN }}
  URL: ${{ secrets.SONAR_HOST_URL }}
 
 
jobs:

    trigger_database: 
      
       uses: viveksundar5/database_sample/.github/workflows/main.yml@main
      
       secrets:
         Workflow2_PAT_TOKEN_GITHUB: ${{ secrets.Workflow2_PAT_TOKEN_GITHUB }}
      
