name: database CI

on:
  workflow_dispatch:
  
jobs:
  trigger_database:
    uses: viveksundar5/database_sample/.github/workflows/main.yml@main
    secrets:
      Workflow2_PAT_TOKEN_GITHUB: ${{ secrets.Workflow2_PAT_TOKEN_GITHUB }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
