name: database CI

on:
 workflow_dispatch:
 
   inputs: |
    -D sonar.projectKey=test-maven-project \
    -D sonar.host.url=$SONAR_HOST_URL \
    -D sonar.login=admin -D sonar.password=admin123 
 
 
jobs:

    trigger_database: 
      
       uses: viveksundar5/database_sample/.github/workflows/main.yml@main
      
       secrets:
         Workflow2_PAT_TOKEN_GITHUB: ${{ secrets.Workflow2_PAT_TOKEN_GITHUB }}
      
