name: database CI

on:
 workflow_dispatch:
 
 
jobs:

    trigger_database: 
      
       uses: viveksundar5/callerworkflow/.github/workflows/main.yml@main
      
       secrets:
         Workflow2_PAT_TOKEN_GITHUB: ${{ secrets.Workflow2_PAT_TOKEN_GITHUB }}
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
